import AppKit
import SwiftUI

// Generates Resources/Assets.xcassets/AppIcon.appiconset.
//
// Committed so the icon has a producer. Every other picture in this
// repository is generated by Tools/Shots, and the one that is not,
// docs/images/shelf.png, cannot be rebuilt by anybody. An app icon is worse
// to lose that way: ten PNGs with no source means the next change to it
// starts in an image editor, guessing at the radii.
//
//   swiftc -O -framework AppKit -framework SwiftUI -framework ImageIO \
//     Tools/IconGen/main.swift -o /tmp/icongen
//   /tmp/icongen Resources/Assets.xcassets/AppIcon.appiconset
//
// The design: a panel anchored above a row of tiles, with a tail pointing
// back at the one it came from. That is the single thing this app does that
// nothing else in a Dock does, so it is what the icon should say. The panel
// holds a figure and a sparkline rather than lines of text, because lines of
// text in a tailed bubble read as a messaging app.

private let canvas: CGFloat = 1024

// macOS does not mask app icons, so the squircle is part of the art. Apple's
// grid leaves it inset with transparent margin around it, which is what makes
// an icon sit correctly beside Apple's own.
private let inset: CGFloat = 100
private let side = canvas - inset * 2
private let corner = side * 0.235

private let mint = Color(red: 0.36, green: 0.85, blue: 0.76)
private let blue = Color(red: 0.22, green: 0.58, blue: 0.93)
private let tailBlue = Color(red: 0.24, green: 0.62, blue: 0.91)

private struct Icon: View {
    var body: some View {
        ZStack {
            RoundedRectangle(cornerRadius: corner, style: .continuous)
                .fill(
                    LinearGradient(colors: [Color(red: 0.16, green: 0.18, blue: 0.24),
                                            Color(red: 0.07, green: 0.08, blue: 0.11)],
                                   startPoint: .top, endPoint: .bottom)
                )
                // A thin light edge along the top is what reads as glass
                // rather than as a flat sticker.
                .overlay {
                    RoundedRectangle(cornerRadius: corner, style: .continuous)
                        .strokeBorder(
                            LinearGradient(colors: [.white.opacity(0.22), .white.opacity(0.02)],
                                           startPoint: .top, endPoint: .bottom),
                            lineWidth: side * 0.006
                        )
                }
                .shadow(color: .black.opacity(0.34), radius: side * 0.045, y: side * 0.022)
            content
        }
        .frame(width: side, height: side)
        .frame(width: canvas, height: canvas)
    }

    private var content: some View {
        VStack(spacing: 0) {
            RoundedRectangle(cornerRadius: side * 0.085, style: .continuous)
                .fill(LinearGradient(colors: [mint, blue],
                                     startPoint: .topLeading, endPoint: .bottomTrailing))
                .frame(width: side * 0.62, height: side * 0.32)
                .overlay {
                    VStack(alignment: .leading, spacing: side * 0.028) {
                        // Stands in for the figure a widget leads with.
                        Capsule().fill(.white.opacity(0.96))
                            .frame(width: side * 0.16, height: side * 0.072)
                        Spark()
                            .stroke(.white.opacity(0.92),
                                    style: StrokeStyle(lineWidth: side * 0.026,
                                                       lineCap: .round, lineJoin: .round))
                            .frame(width: side * 0.42, height: side * 0.095)
                    }
                }
            // Same colour as the panel's bottom edge, so the tail reads as
            // part of one shape rather than a triangle stuck underneath.
            Tail()
                .fill(tailBlue)
                .frame(width: side * 0.105, height: side * 0.055)
            Spacer().frame(height: side * 0.055)
            // The shelf. The lit tile is the one the panel came from, which
            // is what makes the tail mean something.
            HStack(spacing: side * 0.040) {
                tile(.white.opacity(0.30))
                tile(.white.opacity(0.90))
                tile(.white.opacity(0.30))
            }
        }
        .offset(y: side * 0.025)
    }

    private func tile(_ fill: Color) -> some View {
        RoundedRectangle(cornerRadius: side * 0.030, style: .continuous)
            .fill(fill)
            .frame(width: side * 0.125, height: side * 0.125)
    }
}

/// Four points, rising. Few enough that 16pt keeps the shape.
private struct Spark: Shape {
    func path(in r: CGRect) -> Path {
        var p = Path()
        let points = [CGPoint(x: 0.00, y: 0.72), CGPoint(x: 0.33, y: 0.30),
                      CGPoint(x: 0.64, y: 0.58), CGPoint(x: 1.00, y: 0.04)]
        for (i, q) in points.enumerated() {
            let at = CGPoint(x: r.minX + q.x * r.width, y: r.minY + q.y * r.height)
            if i == 0 { p.move(to: at) } else { p.addLine(to: at) }
        }
        return p
    }
}

private struct Tail: Shape {
    func path(in r: CGRect) -> Path {
        var p = Path()
        p.move(to: CGPoint(x: r.minX, y: r.minY))
        p.addLine(to: CGPoint(x: r.maxX, y: r.minY))
        p.addLine(to: CGPoint(x: r.midX, y: r.maxY))
        p.closeSubpath()
        return p
    }
}

/// Exactly the names Contents.json declares. A missing one is a build warning
/// and a blank icon at that size.
private let sizes: [(String, CGFloat)] = [
    ("icon_16x16", 16), ("icon_16x16@2x", 32),
    ("icon_32x32", 32), ("icon_32x32@2x", 64),
    ("icon_128x128", 128), ("icon_128x128@2x", 256),
    ("icon_256x256", 256), ("icon_256x256@2x", 512),
    ("icon_512x512", 512), ("icon_512x512@2x", 1024),
]

@MainActor
private func write(to url: URL, pixels: CGFloat) {
    let renderer = ImageRenderer(content: Icon().frame(width: canvas, height: canvas))
    // Rendered at each size rather than downscaled from one, so the hairline
    // edge and the sparkline are resolved for the pixels they land on.
    renderer.scale = pixels / canvas
    renderer.isOpaque = false
    guard let image = renderer.cgImage,
          let dest = CGImageDestinationCreateWithURL(url as CFURL, "public.png" as CFString, 1, nil)
    else { fatalError("could not render \(url.lastPathComponent)") }
    CGImageDestinationAddImage(dest, image, nil)
    CGImageDestinationFinalize(dest)
}

guard CommandLine.arguments.count > 1 else {
    FileHandle.standardError.write(Data("usage: icongen <AppIcon.appiconset directory>\n".utf8))
    exit(2)
}
let out = URL(fileURLWithPath: CommandLine.arguments[1], isDirectory: true)
try? FileManager.default.createDirectory(at: out, withIntermediateDirectories: true)

MainActor.assumeIsolated {
    for (name, pixels) in sizes {
        write(to: out.appending(path: "\(name).png"), pixels: pixels)
    }
}
print("wrote \(sizes.count) icon files to \(out.path)")
